// (function($){
//     $(document).ready(function(){
//         console.log('ready');
//     });
//     $(window).load(function(){
//         console.log('load');
//     });
//     $(window).resize(function(){
//         console.log('resize');
//     });
// })(window.jQuery);